spring.application.name=examserver
# Run on port 8080
server.port=8080

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/examportal?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

# Hibernate Configuration (Auto-creates tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect